package com.managementsystem.energy.domain;

// Generated 2013-5-3 9:03:00 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Boi generated by hbm2java
 */
public class Boi implements java.io.Serializable {

	private long id;
	private String buildId;
	private String regionId;
	private String position;
	private String deviceNo;
	private String description;
	private String maker;
	private String model;
	private Integer total;
	private BigDecimal hc;
	private BigDecimal frFue;
	private BigDecimal THwS;
	private BigDecimal THwR;
	private BigDecimal frHw;
	private String comment;

	public Boi() {
	}

	public Boi(long id) {
		this.id = id;
	}

	public Boi(long id, String buildId, String regionId, String position,
			String deviceNo, String description, String maker, String model,
			Integer total, BigDecimal hc, BigDecimal frFue, BigDecimal THwS,
			BigDecimal THwR, BigDecimal frHw, String comment) {
		this.id = id;
		this.buildId = buildId;
		this.regionId = regionId;
		this.position = position;
		this.deviceNo = deviceNo;
		this.description = description;
		this.maker = maker;
		this.model = model;
		this.total = total;
		this.hc = hc;
		this.frFue = frFue;
		this.THwS = THwS;
		this.THwR = THwR;
		this.frHw = frHw;
		this.comment = comment;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getBuildId() {
		return this.buildId;
	}

	public void setBuildId(String buildId) {
		this.buildId = buildId;
	}

	public String getRegionId() {
		return this.regionId;
	}

	public void setRegionId(String regionId) {
		this.regionId = regionId;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getDeviceNo() {
		return this.deviceNo;
	}

	public void setDeviceNo(String deviceNo) {
		this.deviceNo = deviceNo;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getMaker() {
		return this.maker;
	}

	public void setMaker(String maker) {
		this.maker = maker;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public Integer getTotal() {
		return this.total;
	}

	public void setTotal(Integer total) {
		this.total = total;
	}

	public BigDecimal getHc() {
		return this.hc;
	}

	public void setHc(BigDecimal hc) {
		this.hc = hc;
	}

	public BigDecimal getFrFue() {
		return this.frFue;
	}

	public void setFrFue(BigDecimal frFue) {
		this.frFue = frFue;
	}

	public BigDecimal getTHwS() {
		return this.THwS;
	}

	public void setTHwS(BigDecimal THwS) {
		this.THwS = THwS;
	}

	public BigDecimal getTHwR() {
		return this.THwR;
	}

	public void setTHwR(BigDecimal THwR) {
		this.THwR = THwR;
	}

	public BigDecimal getFrHw() {
		return this.frHw;
	}

	public void setFrHw(BigDecimal frHw) {
		this.frHw = frHw;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
