package com.managementsystem.energy.domain;

// Generated 2012-6-14 13:19:36 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Buildexinfo generated by hbm2java
 */
public class Buildexinfo implements java.io.Serializable {

	private String buildId;
	private Buildinfo buildinfo;
	private Integer buildWorkernum;
	private Integer buildCustomernum;
	private BigDecimal buildOpenhours;
	private String buildServicelevel;
	private BigDecimal buildHotelliverate;
	private Integer buildHotelbednum;
	private Integer buildVistornum;
	private Integer buildStudentnum;
	private String buildHospitalstandard;
	private String buildHospitaltype;
	private Integer buildPatientnum;
	private Integer buildHospitalbednum;
	private Integer buildSpectaotrnum;
	private String buildGroupfunc;
	private String buildExtendfunc;
	private String buildElectriprice;
	private String buildWaterprice;
	private String buildGasprice;
	private String buildHeatprice;
	private String buildOtherprice;

	public Buildexinfo() {
	}

	public Buildexinfo(Buildinfo buildinfo) {
		this.buildinfo = buildinfo;
	}

	public Buildexinfo(Buildinfo buildinfo, Integer buildWorkernum,
			Integer buildCustomernum, BigDecimal buildOpenhours,
			String buildServicelevel, BigDecimal buildHotelliverate,
			Integer buildHotelbednum, Integer buildVistornum,
			Integer buildStudentnum, String buildHospitalstandard,
			String buildHospitaltype, Integer buildPatientnum,
			Integer buildHospitalbednum, Integer buildSpectaotrnum,
			String buildGroupfunc, String buildExtendfunc,
			String buildElectriprice, String buildWaterprice,
			String buildGasprice, String buildHeatprice, String buildOtherprice) {
		this.buildinfo = buildinfo;
		this.buildWorkernum = buildWorkernum;
		this.buildCustomernum = buildCustomernum;
		this.buildOpenhours = buildOpenhours;
		this.buildServicelevel = buildServicelevel;
		this.buildHotelliverate = buildHotelliverate;
		this.buildHotelbednum = buildHotelbednum;
		this.buildVistornum = buildVistornum;
		this.buildStudentnum = buildStudentnum;
		this.buildHospitalstandard = buildHospitalstandard;
		this.buildHospitaltype = buildHospitaltype;
		this.buildPatientnum = buildPatientnum;
		this.buildHospitalbednum = buildHospitalbednum;
		this.buildSpectaotrnum = buildSpectaotrnum;
		this.buildGroupfunc = buildGroupfunc;
		this.buildExtendfunc = buildExtendfunc;
		this.buildElectriprice = buildElectriprice;
		this.buildWaterprice = buildWaterprice;
		this.buildGasprice = buildGasprice;
		this.buildHeatprice = buildHeatprice;
		this.buildOtherprice = buildOtherprice;
	}

	public String getBuildId() {
		return this.buildId;
	}

	public void setBuildId(String buildId) {
		this.buildId = buildId;
	}

	public Buildinfo getBuildinfo() {
		return this.buildinfo;
	}

	public void setBuildinfo(Buildinfo buildinfo) {
		this.buildinfo = buildinfo;
	}

	public Integer getBuildWorkernum() {
		return this.buildWorkernum;
	}

	public void setBuildWorkernum(Integer buildWorkernum) {
		this.buildWorkernum = buildWorkernum;
	}

	public Integer getBuildCustomernum() {
		return this.buildCustomernum;
	}

	public void setBuildCustomernum(Integer buildCustomernum) {
		this.buildCustomernum = buildCustomernum;
	}

	public BigDecimal getBuildOpenhours() {
		return this.buildOpenhours;
	}

	public void setBuildOpenhours(BigDecimal buildOpenhours) {
		this.buildOpenhours = buildOpenhours;
	}

	public String getBuildServicelevel() {
		return this.buildServicelevel;
	}

	public void setBuildServicelevel(String buildServicelevel) {
		this.buildServicelevel = buildServicelevel;
	}

	public BigDecimal getBuildHotelliverate() {
		return this.buildHotelliverate;
	}

	public void setBuildHotelliverate(BigDecimal buildHotelliverate) {
		this.buildHotelliverate = buildHotelliverate;
	}

	public Integer getBuildHotelbednum() {
		return this.buildHotelbednum;
	}

	public void setBuildHotelbednum(Integer buildHotelbednum) {
		this.buildHotelbednum = buildHotelbednum;
	}

	public Integer getBuildVistornum() {
		return this.buildVistornum;
	}

	public void setBuildVistornum(Integer buildVistornum) {
		this.buildVistornum = buildVistornum;
	}

	public Integer getBuildStudentnum() {
		return this.buildStudentnum;
	}

	public void setBuildStudentnum(Integer buildStudentnum) {
		this.buildStudentnum = buildStudentnum;
	}

	public String getBuildHospitalstandard() {
		return this.buildHospitalstandard;
	}

	public void setBuildHospitalstandard(String buildHospitalstandard) {
		this.buildHospitalstandard = buildHospitalstandard;
	}

	public String getBuildHospitaltype() {
		return this.buildHospitaltype;
	}

	public void setBuildHospitaltype(String buildHospitaltype) {
		this.buildHospitaltype = buildHospitaltype;
	}

	public Integer getBuildPatientnum() {
		return this.buildPatientnum;
	}

	public void setBuildPatientnum(Integer buildPatientnum) {
		this.buildPatientnum = buildPatientnum;
	}

	public Integer getBuildHospitalbednum() {
		return this.buildHospitalbednum;
	}

	public void setBuildHospitalbednum(Integer buildHospitalbednum) {
		this.buildHospitalbednum = buildHospitalbednum;
	}

	public Integer getBuildSpectaotrnum() {
		return this.buildSpectaotrnum;
	}

	public void setBuildSpectaotrnum(Integer buildSpectaotrnum) {
		this.buildSpectaotrnum = buildSpectaotrnum;
	}

	public String getBuildGroupfunc() {
		return this.buildGroupfunc;
	}

	public void setBuildGroupfunc(String buildGroupfunc) {
		this.buildGroupfunc = buildGroupfunc;
	}

	public String getBuildExtendfunc() {
		return this.buildExtendfunc;
	}

	public void setBuildExtendfunc(String buildExtendfunc) {
		this.buildExtendfunc = buildExtendfunc;
	}

	public String getBuildElectriprice() {
		return this.buildElectriprice;
	}

	public void setBuildElectriprice(String buildElectriprice) {
		this.buildElectriprice = buildElectriprice;
	}

	public String getBuildWaterprice() {
		return this.buildWaterprice;
	}

	public void setBuildWaterprice(String buildWaterprice) {
		this.buildWaterprice = buildWaterprice;
	}

	public String getBuildGasprice() {
		return this.buildGasprice;
	}

	public void setBuildGasprice(String buildGasprice) {
		this.buildGasprice = buildGasprice;
	}

	public String getBuildHeatprice() {
		return this.buildHeatprice;
	}

	public void setBuildHeatprice(String buildHeatprice) {
		this.buildHeatprice = buildHeatprice;
	}

	public String getBuildOtherprice() {
		return this.buildOtherprice;
	}

	public void setBuildOtherprice(String buildOtherprice) {
		this.buildOtherprice = buildOtherprice;
	}

}
