package com.managementsystem.energy.domain;

// Generated 2013-5-3 9:03:00 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Chi generated by hbm2java
 */
public class Chi implements java.io.Serializable {

	private long id;
	private String buildId;
	private String regionId;
	private String position;
	private String deviceNo;
	private String description;
	private String maker;
	private String model;
	private Integer total;
	private BigDecimal cap;
	private BigDecimal power;
	private BigDecimal cop;
	private BigDecimal frChw;
	private BigDecimal TChwS;
	private BigDecimal TChwR;
	private BigDecimal frClw;
	private BigDecimal TClwS;
	private BigDecimal TClwR;
	private String comment;

	public Chi() {
	}

	public Chi(long id) {
		this.id = id;
	}

	public Chi(long id, String buildId, String regionId, String position,
			String deviceNo, String description, String maker, String model,
			Integer total, BigDecimal cap, BigDecimal power, BigDecimal cop,
			BigDecimal frChw, BigDecimal TChwS, BigDecimal TChwR,
			BigDecimal frClw, BigDecimal TClwS, BigDecimal TClwR, String comment) {
		this.id = id;
		this.buildId = buildId;
		this.regionId = regionId;
		this.position = position;
		this.deviceNo = deviceNo;
		this.description = description;
		this.maker = maker;
		this.model = model;
		this.total = total;
		this.cap = cap;
		this.power = power;
		this.cop = cop;
		this.frChw = frChw;
		this.TChwS = TChwS;
		this.TChwR = TChwR;
		this.frClw = frClw;
		this.TClwS = TClwS;
		this.TClwR = TClwR;
		this.comment = comment;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getBuildId() {
		return this.buildId;
	}

	public void setBuildId(String buildId) {
		this.buildId = buildId;
	}

	public String getRegionId() {
		return this.regionId;
	}

	public void setRegionId(String regionId) {
		this.regionId = regionId;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getDeviceNo() {
		return this.deviceNo;
	}

	public void setDeviceNo(String deviceNo) {
		this.deviceNo = deviceNo;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getMaker() {
		return this.maker;
	}

	public void setMaker(String maker) {
		this.maker = maker;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public Integer getTotal() {
		return this.total;
	}

	public void setTotal(Integer total) {
		this.total = total;
	}

	public BigDecimal getCap() {
		return this.cap;
	}

	public void setCap(BigDecimal cap) {
		this.cap = cap;
	}

	public BigDecimal getPower() {
		return this.power;
	}

	public void setPower(BigDecimal power) {
		this.power = power;
	}

	public BigDecimal getCop() {
		return this.cop;
	}

	public void setCop(BigDecimal cop) {
		this.cop = cop;
	}

	public BigDecimal getFrChw() {
		return this.frChw;
	}

	public void setFrChw(BigDecimal frChw) {
		this.frChw = frChw;
	}

	public BigDecimal getTChwS() {
		return this.TChwS;
	}

	public void setTChwS(BigDecimal TChwS) {
		this.TChwS = TChwS;
	}

	public BigDecimal getTChwR() {
		return this.TChwR;
	}

	public void setTChwR(BigDecimal TChwR) {
		this.TChwR = TChwR;
	}

	public BigDecimal getFrClw() {
		return this.frClw;
	}

	public void setFrClw(BigDecimal frClw) {
		this.frClw = frClw;
	}

	public BigDecimal getTClwS() {
		return this.TClwS;
	}

	public void setTClwS(BigDecimal TClwS) {
		this.TClwS = TClwS;
	}

	public BigDecimal getTClwR() {
		return this.TClwR;
	}

	public void setTClwR(BigDecimal TClwR) {
		this.TClwR = TClwR;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
