package com.managementsystem.energy.domain;

// Generated 2013-5-3 9:03:00 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Ct generated by hbm2java
 */
public class Ct implements java.io.Serializable {

	private long id;
	private String buildId;
	private String regionId;
	private String position;
	private String deviceNo;
	private String description;
	private String maker;
	private String model;
	private Integer total;
	private BigDecimal frW;
	private BigDecimal frOa;
	private BigDecimal totalF;
	private BigDecimal power;
	private BigDecimal pr;
	private BigDecimal st;
	private BigDecimal rt;
	private BigDecimal oat;
	private BigDecimal oarh;
	private BigDecimal eff;
	private BigDecimal totalHt;
	private BigDecimal powerHt;
	private String comment;

	public Ct() {
	}

	public Ct(long id) {
		this.id = id;
	}

	public Ct(long id, String buildId, String regionId, String position,
			String deviceNo, String description, String maker, String model,
			Integer total, BigDecimal frW, BigDecimal frOa, BigDecimal totalF,
			BigDecimal power, BigDecimal pr, BigDecimal st, BigDecimal rt,
			BigDecimal oat, BigDecimal oarh, BigDecimal eff,
			BigDecimal totalHt, BigDecimal powerHt, String comment) {
		this.id = id;
		this.buildId = buildId;
		this.regionId = regionId;
		this.position = position;
		this.deviceNo = deviceNo;
		this.description = description;
		this.maker = maker;
		this.model = model;
		this.total = total;
		this.frW = frW;
		this.frOa = frOa;
		this.totalF = totalF;
		this.power = power;
		this.pr = pr;
		this.st = st;
		this.rt = rt;
		this.oat = oat;
		this.oarh = oarh;
		this.eff = eff;
		this.totalHt = totalHt;
		this.powerHt = powerHt;
		this.comment = comment;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getBuildId() {
		return this.buildId;
	}

	public void setBuildId(String buildId) {
		this.buildId = buildId;
	}

	public String getRegionId() {
		return this.regionId;
	}

	public void setRegionId(String regionId) {
		this.regionId = regionId;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getDeviceNo() {
		return this.deviceNo;
	}

	public void setDeviceNo(String deviceNo) {
		this.deviceNo = deviceNo;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getMaker() {
		return this.maker;
	}

	public void setMaker(String maker) {
		this.maker = maker;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public Integer getTotal() {
		return this.total;
	}

	public void setTotal(Integer total) {
		this.total = total;
	}

	public BigDecimal getFrW() {
		return this.frW;
	}

	public void setFrW(BigDecimal frW) {
		this.frW = frW;
	}

	public BigDecimal getFrOa() {
		return this.frOa;
	}

	public void setFrOa(BigDecimal frOa) {
		this.frOa = frOa;
	}

	public BigDecimal getTotalF() {
		return this.totalF;
	}

	public void setTotalF(BigDecimal totalF) {
		this.totalF = totalF;
	}

	public BigDecimal getPower() {
		return this.power;
	}

	public void setPower(BigDecimal power) {
		this.power = power;
	}

	public BigDecimal getPr() {
		return this.pr;
	}

	public void setPr(BigDecimal pr) {
		this.pr = pr;
	}

	public BigDecimal getSt() {
		return this.st;
	}

	public void setSt(BigDecimal st) {
		this.st = st;
	}

	public BigDecimal getRt() {
		return this.rt;
	}

	public void setRt(BigDecimal rt) {
		this.rt = rt;
	}

	public BigDecimal getOat() {
		return this.oat;
	}

	public void setOat(BigDecimal oat) {
		this.oat = oat;
	}

	public BigDecimal getOarh() {
		return this.oarh;
	}

	public void setOarh(BigDecimal oarh) {
		this.oarh = oarh;
	}

	public BigDecimal getEff() {
		return this.eff;
	}

	public void setEff(BigDecimal eff) {
		this.eff = eff;
	}

	public BigDecimal getTotalHt() {
		return this.totalHt;
	}

	public void setTotalHt(BigDecimal totalHt) {
		this.totalHt = totalHt;
	}

	public BigDecimal getPowerHt() {
		return this.powerHt;
	}

	public void setPowerHt(BigDecimal powerHt) {
		this.powerHt = powerHt;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
