package com.managementsystem.energy.domain;

// Generated 2013-5-3 9:03:00 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Fcu generated by hbm2java
 */
public class Fcu implements java.io.Serializable {

	private long id;
	private String buildId;
	private String regionId;
	private String position;
	private String deviceNo;
	private String description;
	private String maker;
	private String model;
	private Integer total;
	private BigDecimal power;
	private BigDecimal cc;
	private BigDecimal hc;
	private BigDecimal fr;
	private String comment;

	public Fcu() {
	}

	public Fcu(long id) {
		this.id = id;
	}

	public Fcu(long id, String buildId, String regionId, String position,
			String deviceNo, String description, String maker, String model,
			Integer total, BigDecimal power, BigDecimal cc, BigDecimal hc,
			BigDecimal fr, String comment) {
		this.id = id;
		this.buildId = buildId;
		this.regionId = regionId;
		this.position = position;
		this.deviceNo = deviceNo;
		this.description = description;
		this.maker = maker;
		this.model = model;
		this.total = total;
		this.power = power;
		this.cc = cc;
		this.hc = hc;
		this.fr = fr;
		this.comment = comment;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getBuildId() {
		return this.buildId;
	}

	public void setBuildId(String buildId) {
		this.buildId = buildId;
	}

	public String getRegionId() {
		return this.regionId;
	}

	public void setRegionId(String regionId) {
		this.regionId = regionId;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getDeviceNo() {
		return this.deviceNo;
	}

	public void setDeviceNo(String deviceNo) {
		this.deviceNo = deviceNo;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getMaker() {
		return this.maker;
	}

	public void setMaker(String maker) {
		this.maker = maker;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public Integer getTotal() {
		return this.total;
	}

	public void setTotal(Integer total) {
		this.total = total;
	}

	public BigDecimal getPower() {
		return this.power;
	}

	public void setPower(BigDecimal power) {
		this.power = power;
	}

	public BigDecimal getCc() {
		return this.cc;
	}

	public void setCc(BigDecimal cc) {
		this.cc = cc;
	}

	public BigDecimal getHc() {
		return this.hc;
	}

	public void setHc(BigDecimal hc) {
		this.hc = hc;
	}

	public BigDecimal getFr() {
		return this.fr;
	}

	public void setFr(BigDecimal fr) {
		this.fr = fr;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
