package com.managementsystem.energy.domain;

// Generated 2012-10-30 9:57:33 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Subscription generated by hbm2java
 */
public class Subscription implements java.io.Serializable {

	private String subId;
	private Long groupid;
	private Long companyid;
	private Long userid;
	private String username;
	private String usertype;
	private String subDatasrctype;
	private String subReceiverate;
	private String subReceiveemail;
	private Date createdondate;
	private Date modifiedondate;

	public Subscription() {
	}

	public Subscription(String subId) {
		this.subId = subId;
	}

	public Subscription(String subId, Long groupid, Long companyid,
			Long userid, String username, String usertype,
			String subDatasrctype, String subReceiverate,
			String subReceiveemail, Date createdondate, Date modifiedondate) {
		this.subId = subId;
		this.groupid = groupid;
		this.companyid = companyid;
		this.userid = userid;
		this.username = username;
		this.usertype = usertype;
		this.subDatasrctype = subDatasrctype;
		this.subReceiverate = subReceiverate;
		this.subReceiveemail = subReceiveemail;
		this.createdondate = createdondate;
		this.modifiedondate = modifiedondate;
	}

	public String getSubId() {
		return this.subId;
	}

	public void setSubId(String subId) {
		this.subId = subId;
	}

	public Long getGroupid() {
		return this.groupid;
	}

	public void setGroupid(Long groupid) {
		this.groupid = groupid;
	}

	public Long getCompanyid() {
		return this.companyid;
	}

	public void setCompanyid(Long companyid) {
		this.companyid = companyid;
	}

	public Long getUserid() {
		return this.userid;
	}

	public void setUserid(Long userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getUsertype() {
		return this.usertype;
	}

	public void setUsertype(String usertype) {
		this.usertype = usertype;
	}

	public String getSubDatasrctype() {
		return this.subDatasrctype;
	}

	public void setSubDatasrctype(String subDatasrctype) {
		this.subDatasrctype = subDatasrctype;
	}

	public String getSubReceiverate() {
		return this.subReceiverate;
	}

	public void setSubReceiverate(String subReceiverate) {
		this.subReceiverate = subReceiverate;
	}

	public String getSubReceiveemail() {
		return this.subReceiveemail;
	}

	public void setSubReceiveemail(String subReceiveemail) {
		this.subReceiveemail = subReceiveemail;
	}

	public Date getCreatedondate() {
		return this.createdondate;
	}

	public void setCreatedondate(Date createdondate) {
		this.createdondate = createdondate;
	}

	public Date getModifiedondate() {
		return this.modifiedondate;
	}

	public void setModifiedondate(Date modifiedondate) {
		this.modifiedondate = modifiedondate;
	}

}
